version: '3'

services:
  flervalgsgenerator:
    build: .
    container_name: flervalgsgenerator
    restart: unless-stopped
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./:/app
